variables:
  API_TOKEN: $AZURE_STATIC_WEB_APPS_API_TOKEN
  APP_PATH: '$CI_PROJECT_DIR/src'

deploy:
  stage: deploy
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  script:
    - sed -i 's|YOUR_TENANT_ID|'${TENANT_ID}'|g' staticwebapp.config.json
    - echo "Updated staticwebapp.config.json with TENANT_ID"
    - echo "App deployed successfully."
